require_relative "../helpers.rb"
require_relative "custom_to_es/fields.rb"
require_relative "custom_to_es/request.rb"

#########################################
# NOTE:  DO NOT EDIT THIS FILE!!!!!!!!! #
#########################################
#   (unless you are a CDRH dev and then you may do so very cautiously)
#   this file provides defaults for ALL of the collections included
#   in the API and changing it could alter dozens of sites unexpectedly!
# PLEASE RUN LOADS OF TESTS AFTER A CHANGE BEFORE PUSHING TO PRODUCTION

# WHAT IS THIS FILE?
#   This file sets up default behavior for transforming custom
#   documents to Elasticsearch JSON documents

class CustomToEs

  attr_reader :json, :item, :file_type

  def initialize(item, options: {}, file: nil, filename: nil, file_type: nil)
    @item = item
    @options = options
    # behaves similarly to parent_xml in that it represents
    # the entire file, whereas item MAY represent a portion
    # of a file (as is the case with a csv row, personography
    # //person path, etc)
    @file = file
    @filename = filename
    @file_type = file_type
    @id = get_id

    create_json
  end

  # getter for @json response object
  def create_json
    @json = {}
    # if anything needs to be done before processing
    # do it here (ex: reading in annotations into memory)
    preprocessing
    assemble_json
    postprocessing
  end

  def get_id
    nil
  end

  def preprocessing
    # copy this in your custom_to_es collection file to customize
  end

  def postprocessing
    # copy this in your custom_to_es collection file to customize
  end
end
