require_relative "../helpers.rb"
require_relative "pdf_to_es/fields.rb"
require_relative "pdf_to_es/request.rb"

#########################################
# NOTE:  DO NOT EDIT THIS FILE!!!!!!!!! #
#########################################
#   (unless you are a CDRH dev and then you may do so very cautiously)
#   this file provides defaults for ALL of the collections included
#   in the API and changing it could alter dozens of sites unexpectedly!
# PLEASE RUN LOADS OF TESTS AFTER A CHANGE BEFORE PUSHING TO PRODUCTION

# WHAT IS THIS FILE?
#   This file sets up default behavior for transforming PDF
#   documents to Elasticsearch JSON documents

class PdfToEs

  attr_reader :json, :pdf
  # variables
  # id, row, pdf

  def initialize(pdf, options={}, filename=nil)
    @pdf = pdf
    @options = options
    @filename = filename
    @id = get_id

    create_json
  end

  # getter for @json response object
  def create_json
    @json = {}
    # if anything needs to be done before processing
    # do it here (ex: reading in annotations into memory)
    preprocessing
    assemble_json
    postprocessing
  end

  def get_id
    filename.delete_suffix(".pdf")
  end

  def preprocessing
    # copy this in your csv_to_es collection file to customize
  end

  def postprocessing
    # copy this in your csv_to_es collection file to customize
  end
end
