name: Minitest

on:
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out datura code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # run bundle install
          # cache installed gems
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake test
